import React from 'react'
import PlaylistItem from './PlaylistItem'

const SpotifyPlaylist = () => {

  const songsList = spotifyData.tracks.map((track, index) => {
    return (
      <PlaylistItem
        track={track}
        key={index}
      />
    )
  })

  console.log(songsList);

  return (
    <div className="spotify">
      {songsList}
    </div>
  )
}

export default SpotifyPlaylist

const spotifyData = {
  "tracks": [
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/2UJwKSBUz6rtW4QLK74kQu"
        },
        "href": "https://api.spotify.com/v1/albums/2UJwKSBUz6rtW4QLK74kQu",
        "id": "2UJwKSBUz6rtW4QLK74kQu",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/98be8968e1c29e6ef80831c5867733d2e687b508",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/a986d5fe5780115541b5c33e89ed66272e5d4c0f",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/20787cddd28d8b7335f9cc8baff2b097d27558d1",
            "width": 64
          }
        ],
        "name": "BEYONCÉ [Platinum Edition]",
        "type": "album",
        "uri": "spotify:album:2UJwKSBUz6rtW4QLK74kQu"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 2,
      "duration_ms": 213506,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM11408532"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/02M6vucOvmRfMxTXDUwRXu"
      },
      "href": "https://api.spotify.com/v1/tracks/02M6vucOvmRfMxTXDUwRXu",
      "id": "02M6vucOvmRfMxTXDUwRXu",
      "name": "7/11",
      "popularity": 76,
      "preview_url": "https://p.scdn.co/mp3-preview/c17eaf47f9624029dadcd7672b7896c84923e28c",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:02M6vucOvmRfMxTXDUwRXu"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/6oxVabMIqCMJRYN1GqR3Vf"
        },
        "href": "https://api.spotify.com/v1/albums/6oxVabMIqCMJRYN1GqR3Vf",
        "id": "6oxVabMIqCMJRYN1GqR3Vf",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/4f209f5fa9d4ee65215f0dcc5fb513a4119cef10",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/58ce427aaf12cf21f56be209216b0fb2ac0550f3",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/c41d22c0cca1d4789098c6f203c6acc50c19876c",
            "width": 64
          }
        ],
        "name": "Dangerously In Love",
        "type": "album",
        "uri": "spotify:album:6oxVabMIqCMJRYN1GqR3Vf"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/3nFkdlSjzX9mRTtwJOzDYB"
          },
          "href": "https://api.spotify.com/v1/artists/3nFkdlSjzX9mRTtwJOzDYB",
          "id": "3nFkdlSjzX9mRTtwJOzDYB",
          "name": "JAY Z",
          "type": "artist",
          "uri": "spotify:artist:3nFkdlSjzX9mRTtwJOzDYB"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 236133,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM10305425"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/5IVuqXILoxVWvWEPm82Jxr"
      },
      "href": "https://api.spotify.com/v1/tracks/5IVuqXILoxVWvWEPm82Jxr",
      "id": "5IVuqXILoxVWvWEPm82Jxr",
      "name": "Crazy In Love",
      "popularity": 75,
      "preview_url": "https://p.scdn.co/mp3-preview/ce8ace0ec425840416be78db07cf50dd331eed4f",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:5IVuqXILoxVWvWEPm82Jxr"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AU",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HU",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LV",
          "MC",
          "MT",
          "MX",
          "NI",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PL",
          "PT",
          "PY",
          "SE",
          "SK",
          "SV",
          "TR",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/39P7VD7qlg3Z0ltq60eHp7"
        },
        "href": "https://api.spotify.com/v1/albums/39P7VD7qlg3Z0ltq60eHp7",
        "id": "39P7VD7qlg3Z0ltq60eHp7",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/272c8679a23e1c92b17c176f5470e9c2eca3e4bc",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/2b9b7e14294a1be693e1e8a31f87c63a7b226d08",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/0ed754e4a344661ab363da4c7e58bcce1ffd9967",
            "width": 64
          }
        ],
        "name": "I AM...SASHA FIERCE",
        "type": "album",
        "uri": "spotify:album:39P7VD7qlg3Z0ltq60eHp7"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AU",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HU",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LV",
        "MC",
        "MT",
        "MX",
        "NI",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PL",
        "PT",
        "PY",
        "SE",
        "SK",
        "SV",
        "TR",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 261640,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM10804556"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/4JehYebiI9JE8sR8MisGVb"
      },
      "href": "https://api.spotify.com/v1/tracks/4JehYebiI9JE8sR8MisGVb",
      "id": "4JehYebiI9JE8sR8MisGVb",
      "name": "Halo",
      "popularity": 75,
      "preview_url": "https://p.scdn.co/mp3-preview/3c97985f3736fab6d4abcd2067f346a9b30955fa",
      "track_number": 2,
      "type": "track",
      "uri": "spotify:track:4JehYebiI9JE8sR8MisGVb"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/2UJwKSBUz6rtW4QLK74kQu"
        },
        "href": "https://api.spotify.com/v1/albums/2UJwKSBUz6rtW4QLK74kQu",
        "id": "2UJwKSBUz6rtW4QLK74kQu",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/98be8968e1c29e6ef80831c5867733d2e687b508",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/a986d5fe5780115541b5c33e89ed66272e5d4c0f",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/20787cddd28d8b7335f9cc8baff2b097d27558d1",
            "width": 64
          }
        ],
        "name": "BEYONCÉ [Platinum Edition]",
        "type": "album",
        "uri": "spotify:album:2UJwKSBUz6rtW4QLK74kQu"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/3nFkdlSjzX9mRTtwJOzDYB"
          },
          "href": "https://api.spotify.com/v1/artists/3nFkdlSjzX9mRTtwJOzDYB",
          "id": "3nFkdlSjzX9mRTtwJOzDYB",
          "name": "JAY Z",
          "type": "artist",
          "uri": "spotify:artist:3nFkdlSjzX9mRTtwJOzDYB"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 323480,
      "explicit": true,
      "external_ids": {
        "isrc": "USSM11307800"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/6jG2YzhxptolDzLHTGLt7S"
      },
      "href": "https://api.spotify.com/v1/tracks/6jG2YzhxptolDzLHTGLt7S",
      "id": "6jG2YzhxptolDzLHTGLt7S",
      "name": "Drunk in Love",
      "popularity": 74,
      "preview_url": "https://p.scdn.co/mp3-preview/7052c45ae9298c38fdbd1b45bec7fc5f554fafa0",
      "track_number": 3,
      "type": "track",
      "uri": "spotify:track:6jG2YzhxptolDzLHTGLt7S"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/1gIC63gC3B7o7FfpPACZQJ"
        },
        "href": "https://api.spotify.com/v1/albums/1gIC63gC3B7o7FfpPACZQJ",
        "id": "1gIC63gC3B7o7FfpPACZQJ",
        "images": [
          {
            "height": 636,
            "url": "https://i.scdn.co/image/03f017a0243f8700181a566c8201a0ee992a9e91",
            "width": 640
          },
          {
            "height": 298,
            "url": "https://i.scdn.co/image/54df752c9a96b554e448bc187bd16f5a73235c18",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/86e47cbbbbdd1273c5ed479bc0c332f13f5869dd",
            "width": 64
          }
        ],
        "name": "4",
        "type": "album",
        "uri": "spotify:album:1gIC63gC3B7o7FfpPACZQJ"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 236093,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM11102447"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/1uXbwHHfgsXcUKfSZw5ZJ0"
      },
      "href": "https://api.spotify.com/v1/tracks/1uXbwHHfgsXcUKfSZw5ZJ0",
      "id": "1uXbwHHfgsXcUKfSZw5ZJ0",
      "name": "Run the World (Girls)",
      "popularity": 74,
      "preview_url": "https://p.scdn.co/mp3-preview/c5e90d8d93467fc4aeda29c2cbefaa494081232a",
      "track_number": 11,
      "type": "track",
      "uri": "spotify:track:1uXbwHHfgsXcUKfSZw5ZJ0"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/2UJwKSBUz6rtW4QLK74kQu"
        },
        "href": "https://api.spotify.com/v1/albums/2UJwKSBUz6rtW4QLK74kQu",
        "id": "2UJwKSBUz6rtW4QLK74kQu",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/98be8968e1c29e6ef80831c5867733d2e687b508",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/a986d5fe5780115541b5c33e89ed66272e5d4c0f",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/20787cddd28d8b7335f9cc8baff2b097d27558d1",
            "width": 64
          }
        ],
        "name": "BEYONCÉ [Platinum Edition]",
        "type": "album",
        "uri": "spotify:album:2UJwKSBUz6rtW4QLK74kQu"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 369040,
      "explicit": true,
      "external_ids": {
        "isrc": "USSM11307799"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/7cioKB5CHVzk09SOtTyn0T"
      },
      "href": "https://api.spotify.com/v1/tracks/7cioKB5CHVzk09SOtTyn0T",
      "id": "7cioKB5CHVzk09SOtTyn0T",
      "name": "Haunted",
      "popularity": 63,
      "preview_url": "https://p.scdn.co/mp3-preview/63fcd43b454b1dc9c98a3e29b02f66755639a16f",
      "track_number": 2,
      "type": "track",
      "uri": "spotify:track:7cioKB5CHVzk09SOtTyn0T"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/5O7PYNgE3VLWrvB80fIaDZ"
        },
        "href": "https://api.spotify.com/v1/albums/5O7PYNgE3VLWrvB80fIaDZ",
        "id": "5O7PYNgE3VLWrvB80fIaDZ",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/3e29447818ee0648948e3c7f69607d86cc4b63f1",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/d354fa70eee963a6cbb3c59de62bce0ffa5878ad",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/70b639e8ba146827f50b386d4946d93ca0e41c2c",
            "width": 64
          }
        ],
        "name": "I Am...World Tour",
        "type": "album",
        "uri": "spotify:album:5O7PYNgE3VLWrvB80fIaDZ"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 179893,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM11004427"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/1szpCmZZQemziInTY8EXpH"
      },
      "href": "https://api.spotify.com/v1/tracks/1szpCmZZQemziInTY8EXpH",
      "id": "1szpCmZZQemziInTY8EXpH",
      "name": "Diva - Live",
      "popularity": 47,
      "preview_url": "https://p.scdn.co/mp3-preview/0b642e3e2a6730a717ad2e5ce57e5526b76dc283",
      "track_number": 10,
      "type": "track",
      "uri": "spotify:track:1szpCmZZQemziInTY8EXpH"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/2UJwKSBUz6rtW4QLK74kQu"
        },
        "href": "https://api.spotify.com/v1/albums/2UJwKSBUz6rtW4QLK74kQu",
        "id": "2UJwKSBUz6rtW4QLK74kQu",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/98be8968e1c29e6ef80831c5867733d2e687b508",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/a986d5fe5780115541b5c33e89ed66272e5d4c0f",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/20787cddd28d8b7335f9cc8baff2b097d27558d1",
            "width": 64
          }
        ],
        "name": "BEYONCÉ [Platinum Edition]",
        "type": "album",
        "uri": "spotify:album:2UJwKSBUz6rtW4QLK74kQu"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 391906,
      "explicit": true,
      "external_ids": {
        "isrc": "USSM11307805"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/0755vnFQZLSgHHWbR1qCjY"
      },
      "href": "https://api.spotify.com/v1/tracks/0755vnFQZLSgHHWbR1qCjY",
      "id": "0755vnFQZLSgHHWbR1qCjY",
      "name": "Rocket",
      "popularity": 60,
      "preview_url": "https://p.scdn.co/mp3-preview/6cfb3e2c4692a50e5663cc2134b20e146284e28b",
      "track_number": 8,
      "type": "track",
      "uri": "spotify:track:0755vnFQZLSgHHWbR1qCjY"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "CA",
          "CH",
          "HK",
          "ID",
          "LI",
          "MY",
          "PH",
          "SG",
          "TW",
          "US"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/7sJrStyxsdgeQOUlBszizA"
        },
        "href": "https://api.spotify.com/v1/albums/7sJrStyxsdgeQOUlBszizA",
        "id": "7sJrStyxsdgeQOUlBszizA",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/64d6720f222eee638b21b4ed9dbd6f576a512519",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/0c815aca65678f4dce0f11acc80b7c8c8dd38677",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/aef02ed14611934a98e7db3c0a5c06a864064a75",
            "width": 64
          }
        ],
        "name": "Above And Beyoncé Dance Mixes",
        "type": "album",
        "uri": "spotify:album:7sJrStyxsdgeQOUlBszizA"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/2CiaxuTJEkikti5rbhQTZT"
          },
          "href": "https://api.spotify.com/v1/artists/2CiaxuTJEkikti5rbhQTZT",
          "id": "2CiaxuTJEkikti5rbhQTZT",
          "name": "DJ Escape for Escape Productions",
          "type": "artist",
          "uri": "spotify:artist:2CiaxuTJEkikti5rbhQTZT"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5ppooyovqKz6dswneb9MyC"
          },
          "href": "https://api.spotify.com/v1/artists/5ppooyovqKz6dswneb9MyC",
          "id": "5ppooyovqKz6dswneb9MyC",
          "name": "Tony Coluccio for Global Media Music",
          "type": "artist",
          "uri": "spotify:artist:5ppooyovqKz6dswneb9MyC"
        }
      ],
      "available_markets": [
        "CA",
        "CH",
        "HK",
        "ID",
        "LI",
        "MY",
        "PH",
        "SG",
        "TW",
        "US"
      ],
      "disc_number": 1,
      "duration_ms": 413826,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM10805309"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/5JBO0K69Vk2a15zEGhz1vg"
      },
      "href": "https://api.spotify.com/v1/tracks/5JBO0K69Vk2a15zEGhz1vg",
      "id": "5JBO0K69Vk2a15zEGhz1vg",
      "name": "Single Ladies (Put a Ring on It) - DJ Escape & Tony Coluccio Remix - Club Version",
      "popularity": 35,
      "preview_url": "https://p.scdn.co/mp3-preview/0083fac68a7ec4000ff3700b6be44179b49ac05c",
      "track_number": 2,
      "type": "track",
      "uri": "spotify:track:5JBO0K69Vk2a15zEGhz1vg"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HN",
          "HU",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LV",
          "MC",
          "MT",
          "MX",
          "NI",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PL",
          "PT",
          "PY",
          "SE",
          "SK",
          "SV",
          "TR",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/23Y5wdyP5byMFktZf8AcWU"
        },
        "href": "https://api.spotify.com/v1/albums/23Y5wdyP5byMFktZf8AcWU",
        "id": "23Y5wdyP5byMFktZf8AcWU",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/e2a1248d8590c15f5290f0580228918dba52302a",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ce02e64a7d916f9b3b40cb9d5dc3c256c2191474",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/b46e9463d057b673de7d15764ea12b88488bc292",
            "width": 64
          }
        ],
        "name": "I AM...SASHA FIERCE",
        "type": "album",
        "uri": "spotify:album:23Y5wdyP5byMFktZf8AcWU"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HN",
        "HU",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LV",
        "MC",
        "MT",
        "MX",
        "NI",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PL",
        "PT",
        "PY",
        "SE",
        "SK",
        "SV",
        "TR",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 249146,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM10803202"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/26NX1wPt1TRCH536yocd6i"
      },
      "href": "https://api.spotify.com/v1/tracks/26NX1wPt1TRCH536yocd6i",
      "id": "26NX1wPt1TRCH536yocd6i",
      "name": "If I Were a Boy",
      "popularity": 67,
      "preview_url": "https://p.scdn.co/mp3-preview/f12c28a584052bea2731e3589644a77165b02f7c",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:26NX1wPt1TRCH536yocd6i"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/0Zd10MKN5j9KwUST0TdBBB"
        },
        "href": "https://api.spotify.com/v1/albums/0Zd10MKN5j9KwUST0TdBBB",
        "id": "0Zd10MKN5j9KwUST0TdBBB",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ce2a146c4afd781312ee71078c8565b709fff913",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/1382b518456186d5d834193d75ec0f7273de82a5",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/4a0538f456b1ad74dc8e47867cab454a1a20e649",
            "width": 64
          }
        ],
        "name": "B'Day Deluxe Edition",
        "type": "album",
        "uri": "spotify:album:0Zd10MKN5j9KwUST0TdBBB"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 227853,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM10603620"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/6RX5iL93VZ5fKmyvNXvF1r"
      },
      "href": "https://api.spotify.com/v1/tracks/6RX5iL93VZ5fKmyvNXvF1r",
      "id": "6RX5iL93VZ5fKmyvNXvF1r",
      "name": "Irreplaceable",
      "popularity": 69,
      "preview_url": "https://p.scdn.co/mp3-preview/b1cd9ecf3b5108363846f497897b5bcbec44343a",
      "track_number": 2,
      "type": "track",
      "uri": "spotify:track:6RX5iL93VZ5fKmyvNXvF1r"
    },
    {
      "album": {
        "album_type": "album",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/77eZ5eMEh3U0KWricrbevO"
        },
        "href": "https://api.spotify.com/v1/albums/77eZ5eMEh3U0KWricrbevO",
        "id": "77eZ5eMEh3U0KWricrbevO",
        "images": [
          {
            "height": 636,
            "url": "https://i.scdn.co/image/7b21c2705aeb795d15e9fcb3b1bcaa027b24ad1f",
            "width": 640
          },
          {
            "height": 298,
            "url": "https://i.scdn.co/image/9fdb5e32ad56156653c1b8f6ba78c6e49cef5431",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/0b729e4994cabe96010850745aceec50aed94214",
            "width": 64
          }
        ],
        "name": "B'Day",
        "type": "album",
        "uri": "spotify:album:77eZ5eMEh3U0KWricrbevO"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 200533,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM10603615"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/3IAyQMTYOsspp9p1htFSak"
      },
      "href": "https://api.spotify.com/v1/tracks/3IAyQMTYOsspp9p1htFSak",
      "id": "3IAyQMTYOsspp9p1htFSak",
      "name": "Freakum Dress",
      "popularity": 44,
      "preview_url": "https://p.scdn.co/mp3-preview/cb8a76f0ff6de2a57b2fff99415b3ab2017ee2d6",
      "track_number": 7,
      "type": "track",
      "uri": "spotify:track:3IAyQMTYOsspp9p1htFSak"
    },
    {
      "album": {
        "album_type": "single",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/1JSCfr9YFx7SAP8sAYS5vx"
        },
        "href": "https://api.spotify.com/v1/albums/1JSCfr9YFx7SAP8sAYS5vx",
        "id": "1JSCfr9YFx7SAP8sAYS5vx",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/1f49ad5b4139157dc7ae9422219eddc01858c703",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/489763b7fc7cbf240efccd959aae8be8a27b3af8",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/91da53ece7262794afb94a2359e8480a1094f143",
            "width": 64
          }
        ],
        "name": "Crazy In Love (Remix)",
        "type": "album",
        "uri": "spotify:album:1JSCfr9YFx7SAP8sAYS5vx"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 226400,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM11410272"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/2f4IuijXLxYOeBncS60GUD"
      },
      "href": "https://api.spotify.com/v1/tracks/2f4IuijXLxYOeBncS60GUD",
      "id": "2f4IuijXLxYOeBncS60GUD",
      "name": "Crazy In Love - Remix",
      "popularity": 66,
      "preview_url": "https://p.scdn.co/mp3-preview/ac99e5740a6cfdd06be16fbaefbd29a026965e48",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:2f4IuijXLxYOeBncS60GUD"
    },
    {
      "album": {
        "album_type": "single",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/1hq4Vrcbua3DDBLhuWFEVQ"
        },
        "href": "https://api.spotify.com/v1/albums/1hq4Vrcbua3DDBLhuWFEVQ",
        "id": "1hq4Vrcbua3DDBLhuWFEVQ",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/1887ae913ee39a74fa7e6a48abda032d5ce443c2",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/69fa06b84f544bcc34cdd4a0c4c105f70b79d3c3",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/f1125d81b9ec939421d46dda854d4f22ec58a6ad",
            "width": 64
          }
        ],
        "name": "Partition",
        "type": "album",
        "uri": "spotify:album:1hq4Vrcbua3DDBLhuWFEVQ"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 319466,
      "explicit": true,
      "external_ids": {
        "isrc": "USSM11307803"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/2vPTtiR7x7T6Lr17CE2FAE"
      },
      "href": "https://api.spotify.com/v1/tracks/2vPTtiR7x7T6Lr17CE2FAE",
      "id": "2vPTtiR7x7T6Lr17CE2FAE",
      "name": "Partition",
      "popularity": 62,
      "preview_url": "https://p.scdn.co/mp3-preview/8ecd5010e5a46f1c84f42bcfed50505395825d7a",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:2vPTtiR7x7T6Lr17CE2FAE"
    },
    {
      "album": {
        "album_type": "single",
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "SE",
          "SG",
          "SK",
          "SV",
          "TR",
          "TW",
          "US",
          "UY"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/10w5joVHMAc9WMfGrQQMmo"
        },
        "href": "https://api.spotify.com/v1/albums/10w5joVHMAc9WMfGrQQMmo",
        "id": "10w5joVHMAc9WMfGrQQMmo",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/a253e823af2f558b7e46a59e4aa86f7db602a9d6",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/c09000b55810ef4a9b964c5413d02bbac1213830",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/13c4e8d0c5551a92d017c9dac3d5633b0a5ef411",
            "width": 64
          }
        ],
        "name": "Fever",
        "type": "album",
        "uri": "spotify:album:10w5joVHMAc9WMfGrQQMmo"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "SE",
        "SG",
        "SK",
        "SV",
        "TR",
        "TW",
        "US",
        "UY"
      ],
      "disc_number": 1,
      "duration_ms": 212893,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM11000209"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/2Y36tgwhi4gykzF0jXwYH2"
      },
      "href": "https://api.spotify.com/v1/tracks/2Y36tgwhi4gykzF0jXwYH2",
      "id": "2Y36tgwhi4gykzF0jXwYH2",
      "name": "Fever",
      "popularity": 39,
      "preview_url": "https://p.scdn.co/mp3-preview/216e656eb9c0762a1a0204788eed5328a44a44a8",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:2Y36tgwhi4gykzF0jXwYH2"
    },
    {
      "album": {
        "album_type": "single",
        "available_markets": [
          "CA",
          "US"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/1zAuMqjg441b11Gt4BsUWR"
        },
        "href": "https://api.spotify.com/v1/albums/1zAuMqjg441b11Gt4BsUWR",
        "id": "1zAuMqjg441b11Gt4BsUWR",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/3599c68f8ff1f3c8b691069828be8c1787c6f436",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/a22f8045de7d24ec10f7ca28dfd0110b4f928beb",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/013be4ec4534dfe1b1919b466b5b6d3ddbbabd32",
            "width": 64
          }
        ],
        "name": "Telephone (The Remixes, All Partners Version)",
        "type": "album",
        "uri": "spotify:album:1zAuMqjg441b11Gt4BsUWR"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms"
          },
          "href": "https://api.spotify.com/v1/artists/1HY2Jd0NmPuamShAr6KMms",
          "id": "1HY2Jd0NmPuamShAr6KMms",
          "name": "Lady Gaga",
          "type": "artist",
          "uri": "spotify:artist:1HY2Jd0NmPuamShAr6KMms"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m"
          },
          "href": "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          "id": "6vWDO969PvNqNYHIOW5v0m",
          "name": "Beyoncé",
          "type": "artist",
          "uri": "spotify:artist:6vWDO969PvNqNYHIOW5v0m"
        }
      ],
      "available_markets": [
        "CA",
        "US"
      ],
      "disc_number": 1,
      "duration_ms": 401026,
      "explicit": false,
      "external_ids": {
        "isrc": "USUM71001589"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/109dsaRwwWYNBaKKnnYcJN"
      },
      "href": "https://api.spotify.com/v1/tracks/109dsaRwwWYNBaKKnnYcJN",
      "id": "109dsaRwwWYNBaKKnnYcJN",
      "name": "Telephone - Alphabeat Extended Remix",
      "popularity": 27,
      "preview_url": "https://p.scdn.co/mp3-preview/0475fc7b4c5c55737763c42720317df12a11f9d1",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:109dsaRwwWYNBaKKnnYcJN"
    }
  ]
}
